# Fixed size Arrays in Python
List in Python are dynamic Arrays, meaning they can easily change size when you add elements or evendelete them. This is similar to the behavior of Dynamic arrays in C, Vectors in C and Java. But Python Base implementation does not support Fixed Size arrays\
In the next code section, we will use numpy arrays as they provide fixed size arrays to implement the behavior of a dynamic array.\
To acheive this:
1. Create an array of predetermined size
2. Maintain 2 variables
    - length: number of populated elements in array
    - Size: number of total elements in array
3. In a loop:
    - Prompt user for value to insert, and position of insertion
    - If length is less than size, do the insertion - do not forgot to do shifting if needed
    - if length is equal to size, a larger array needs to be created, the old array will then be copied to the new array, and finally the insertion is done
    - Prompt the user if they want to insert more data, Yes takes you back to begining of loop, and No breaks and eand the program

In [4]:
# 1,2

import numpy as np

class MyArray:
    def __init__(self, size):
        self.size = size
        self.data = np.zeros(size)
        self.length = 0

In [5]:
# 3 - implement the append method

class MyArray:
    def __init__(self, size):
        self.size = size
        self.data = np.zeros(size)
        self.length = 0

    def append(self, value):
        if self.length < self.size:
            self.data[self.length] = value
            self.length += 1
        else:
            newdata = np.zeros(self.size * 2)
            for i in range(self.size):
                newdata[i] = self.data[i]
            self.data = newdata
            self.size *= 2
            self.data[self.length] = value
            self.length += 1

In [6]:
# 3 - loop requesting user input

myarray = MyArray(5)
done = False
while not done:
    value = input("Enter a value: ")
    if value == "done":
        done = True
    else:
        myarray.append(float(value))
    print(myarray.data, myarray.length, myarray.size)

[0. 0. 0. 0. 0.] 1 5
[0. 1. 0. 0. 0.] 2 5
[0. 1. 2. 0. 0.] 3 5
[0. 1. 2. 3. 0.] 4 5
[0. 1. 2. 3. 4.] 5 5
[0. 1. 2. 3. 4. 6. 0. 0. 0. 0.] 6 10
[0. 1. 2. 3. 4. 6. 7. 0. 0. 0.] 7 10
[0. 1. 2. 3. 4. 6. 7. 8. 0. 0.] 8 10
[0. 1. 2. 3. 4. 6. 7. 8. 8. 0.] 9 10
[0. 1. 2. 3. 4. 6. 7. 8. 8. 9.] 10 10
[ 0.  1.  2.  3.  4.  6.  7.  8.  8.  9. 10.  0.  0.  0.  0.  0.  0.  0.
  0.  0.] 11 20


ValueError: could not convert string to float: 'blah'